CREATE TABLE IF NOT EXISTS users
(
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(60) NOT NULL,
    image VARCHAR(100) NOT NULL DEFAULT 'no-user.jpg'
) DEFAULT CHARSET utf8;